# Generated by Django 4.1.4 on 2022-12-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_allsociallinks_allsociallink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='company_name',
        ),
        migrations.AddField(
            model_name='allsociallink',
            name='company_name',
            field=models.CharField(default='DreamyCastle', max_length=50),
            preserve_default=False,
        ),
    ]
