# Generated by Django 4.1.4 on 2022-12-19 09:42

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=2, upload_to=blog.models.blog_directory_path),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommentReaply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaply', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agentprofile')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
            ],
        ),
    ]
