# Generated by Django 4.1.4 on 2022-12-19 09:45

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=35)),
                ('locations', models.CharField(max_length=50)),
                ('property_description', models.TextField()),
                ('property_type', models.CharField(choices=[('house', 'House'), ('hotel', 'Hotel'), ('resturent', 'Resturent')], max_length=10)),
                ('status', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=10)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('balcony', 'Balcony'), ('outdoor-kitchen', 'Outdoor Kitchen'), ('cable-tv', 'Cable Tv'), ('deck', 'Deck'), ('tennis-courts', 'Tennis Courts'), ('internet', 'Internet'), ('parking', 'Parking'), ('sun-room', 'Sun Room'), ('concrete-flooring', 'Concrete Flooring')], max_length=25)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('number_of_bed', models.IntegerField()),
                ('number_of_bath', models.IntegerField()),
                ('number_of_garage', models.IntegerField()),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to=property.models.floor_plan_directory_path)),
                ('video_url', models.URLField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img\\property-1.jpg', upload_to=property.models.property_directory_path)),
                ('alt', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
