# Generated by Django 4.1.4 on 2022-12-19 09:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('balcony', 'Balcony'), ('outdoor-kitchen', 'Outdoor Kitchen'), ('cable-tv', 'Cable Tv'), ('deck', 'Deck'), ('tennis-courts', 'Tennis Courts'), ('internet', 'Internet'), ('parking', 'Parking'), ('sun-room', 'Sun Room'), ('concrete-flooring', 'Concrete Flooring')], max_length=250),
        ),
    ]
