# Generated by Django 4.1.4 on 2022-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=454564.43, max_digits=10),
            preserve_default=False,
        ),
    ]
