# Generated by Django 4.1.4 on 2022-12-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_price'),
        ('agent', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
            preserve_default=False,
        ),
    ]
